// Generated by https://quicktype.io

export interface PokemonPageResponse {
    count:    number;
    next:     string;
    previous: null;
    results:  PokemonNameUrl[];
}

export interface PokemonNameUrl {
    name: string;
    url:  string;
}

export interface SimplePokemon {
    id:string;
    name: string;
    imageUrl:  string;
    color?:string;
}
